=== Fercho1992/wangyuhere/trunk/ID2208/JobService/web/university/Transcripts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/Transcripts"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:transcripts="http://www.example.org/Transcripts">

	<import></import>
	<element name="transcripts" type="transcripts:transcriptsType"></element>

	<complexType name="transcriptsType">
		<sequence>
			<element name="transcript"
				type="transcripts:transcriptType">
			</element>
		</sequence>
	</complexType>

	<complexType name="transcriptType">
		<sequence>
			<element name="name" type="string"></element>
			<element name="university" type="string"></element>
			<element name="degree" type="transcripts:degreeType"></element>
			<element name="courses" type="transcripts:coursesType"></element>
		</sequence>
	</complexType>

	<complexType name="coursesType">
		<sequence>
			<element name="course" type="transcripts:courseType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="courseType">
		<sequence>
			<element name="course_name" type="string"></element>
			<element name="grade" type="transcripts:gradeType"></element>
			<element name="ect" type="transcripts:ectType"></element>
		</sequence>
	</complexType>


	<simpleType name="gradeType">
		<restriction base="string">
			<pattern value="[A-F]"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="ectType">
		<restriction base="decimal">
			<fractionDigits value="1"></fractionDigits>
		</restriction>
	</simpleType>

	<simpleType name="degreeType">
		<restriction base="string">
			<enumeration value="Bachelor"></enumeration>
			<enumeration value="Master"></enumeration>
			<enumeration value="Doctor"></enumeration>
		</restriction>
	</simpleType>

</schema>

=== Fercho1992/wangyuhere/ID2208/JobService/xml/Transcripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcripts:transcripts xmlns:transcripts="http://www.example.org/Transcripts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Transcripts Transcripts.xsd ">
  <transcript>
    <name>Trevor</name>
    <university>KTH</university>
    <degree>Master</degree>
    <courses>
    	<course>
    		<course_name>Web Services</course_name>
    		<grade>A</grade>
    		<ect>7.5</ect>
    	</course>
    	<course>
    		<course_name>Java</course_name>
    		<grade>C</grade>
    		<ect>7.5</ect>
    	</course>
    	<course>
    		<course_name>C</course_name>
    		<grade>B</grade>
    		<ect>7.5</ect>
    	</course>
    	<course>
    		<course_name>Software Engineering</course_name>
    		<grade>B</grade>
    		<ect>7.5</ect>
    	</course></courses>
  </transcript>
</transcripts:transcripts>

=== Fercho1992/wangyuhere/trunk/ID2208/XMLProcessing/xml/Transcripts.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcripts:transcripts xmlns:transcripts="http://www.example.org/Transcripts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Transcripts Transcripts.xsd ">
	<transcripts:transcript>
		<transcripts:name>John</transcripts:name>
		<transcripts:university>KTH</transcripts:university>
		<transcripts:degree>Master</transcripts:degree>
		<transcripts:courses>
			<transcripts:course>
				<transcripts:course_name>Web Service</transcripts:course_name>
				<transcripts:grade>A</transcripts:grade>
				<transcripts:ect>7.5</transcripts:ect>
			</transcripts:course>
			<transcripts:course>
				<transcripts:course_name>Modern Method</transcripts:course_name>
				<transcripts:grade>B</transcripts:grade>
				<transcripts:ect>7.5</transcripts:ect>
			</transcripts:course>
		</transcripts:courses>
	</transcripts:transcript>
</transcripts:transcripts>

=== Fercho1992/wangyuhere/ID2208/JobService/web/university/Andy.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcripts:transcripts xmlns:transcripts="http://www.example.org/Transcripts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Transcripts Transcripts.xsd ">
  <transcript>
    <name>Andy</name>
    <university>CTH</university>
    <degree>Master</degree>
    <courses>
    	<course>
    		<course_name>Distributed System</course_name>
    		<grade>B</grade>
    		<ect>7.5</ect>
    	</course>
    	<course>
    		<course_name>MultiAgentSystem</course_name>
    		<grade>A</grade>
    		<ect>7.5</ect>
    	</course>
    	<course>
    		<course_name>C</course_name>
    		<grade>B</grade>
    		<ect>7.5</ect>
    	</course>
    	<course>
    		<course_name>Software Engineering</course_name>
    		<grade>C</grade>
    		<ect>7.5</ect>
    	</course></courses>
  </transcript>
</transcripts:transcripts>
