=== Fercho1992/wangyuhere/ID2208/XMLProcessing/xml/EmplymentRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/EmploymentRecord"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:employmentRecord="http://www.example.org/EmploymentRecord">


    <element name="employmentRecord" type="employmentRecord:recordType"></element>


    <complexType name="recordType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="age" type="integer"></element>
    		<element name="companies"
    			type="employmentRecord:companiesType">
    		</element>
    	</sequence>

    	<attribute name="currentEmployment" type="string" default="NO"></attribute>
    </complexType>

    <complexType name="companiesType">
    	<sequence>
    		<element name="company" type="employmentRecord:companyType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    		
    	</sequence>
    </complexType>
    
    <complexType name="companyType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="positionorTitle" type="string"></element>
    		<element name="lengthofTime" type="string"></element>
    	</sequence>
    </complexType>
    



    <simpleType name="positionType">
    	<restriction base="string">
    		<enumeration value="Technical"></enumeration>
    		<enumeration value="Management"></enumeration>
    		<enumeration value="Sales"></enumeration>
    	</restriction>
    </simpleType>
</schema>

=== Fercho1992/wangyuhere/trunk/ID2208/XMLProcessing/xml/EmploymentRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<employmentRecord:employmentRecord xmlns:companyInfo="http://www.example.org/CompanyInfo" xmlns:employmentRecord="http://www.example.org/EmploymentRecord" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/EmploymentRecord EmplymentRecord.xsd ">
  <employmentRecord:name>Trevor</employmentRecord:name>
  <employmentRecord:age>26</employmentRecord:age>
  <employmentRecord:companies>
    <employmentRecord:company name="Ericsson">
      <companyInfo:classification>IT</companyInfo:classification>
      <companyInfo:region>domestic</companyInfo:region>
      <employmentRecord:name>Trevor</employmentRecord:name>
      <employmentRecord:positionorTitle>programmer</employmentRecord:positionorTitle>
      <employmentRecord:lengthofTime>2years</employmentRecord:lengthofTime>
    </employmentRecord:company>
  </employmentRecord:companies>
</employmentRecord:employmentRecord>
