=== Fercho1992/wangyuhere/trunk/ID2208/XMLProcessing/xml/JobDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/JobDescription" xmlns:tns="http://www.example.org/JobDescription" elementFormDefault="qualified">

    <element name="jobs" type="tns:jobsType"></element>

	<complexType name="jobsType">
    	<sequence>
    		<element name="job" type="tns:jobType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="jobType">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="description" type="string"></element>
    	</sequence>
    </complexType>

</schema>

=== Fercho1992/wangyuhere/trunk/ID2208/XMLProcessing/xml/JobDescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:jobs xmlns:tns="http://www.example.org/JobDescription" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/JobDescription JobDescription.xsd ">
	<tns:job>
		<tns:name>Web Service Engineer</tns:name>
		<tns:description>Building web services</tns:description>
	</tns:job>
	<tns:job>
		<tns:name>Progrommer</tns:name>
		<tns:description>Do java C++ C# programming</tns:description>
	</tns:job>
	<tns:job>
		<tns:name>Ericsson Product Manager</tns:name>
		<tns:description>Product Manager</tns:description>
	</tns:job>
	<tns:job>
		<tns:name>Senior Java Programmer</tns:name>
		<tns:description>A senior java programmer</tns:description>
	</tns:job>
	<tns:job>
		<tns:name>Web Programmer</tns:name>
		<tns:description>PHP MySQL</tns:description>
	</tns:job>
	<tns:job>
		<tns:name>Chef Cook</tns:name>
		<tns:description>Cook in a french restaurant</tns:description>
	</tns:job>
</tns:jobs>
