=== Fercho1992/wangyuhere/trunk/ID2208/XMLProcessing/xml/Transcript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/Transcript"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:transcript="http://www.example.org/Transcript">

    <element name="transcript" type="transcript:transcriptType"></element>

	<complexType name="transcriptType">
		<sequence>
			<element name="name" type="string"></element>
			<element name="university" type="string"></element>
			<element name="degree" type="transcript:degreeType"></element>
			<element name="courses" type="transcript:coursesType"></element>
		</sequence>
	</complexType>

	<complexType name="coursesType">
		<sequence>
			<element name="course" type="transcript:courseType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
    	</sequence>
	</complexType>

	<complexType name="courseType">
		<sequence>
			<element name="course_name" type="string"></element>
			<element name="grade" type="transcript:gradeType"></element>
			<element name="ect" type="transcript:ectType"></element>
		</sequence>
	</complexType>
      

    <simpleType name="gradeType">
    	<restriction base="string">
    		<pattern value="[A-F]"></pattern>
    	</restriction>
    </simpleType>

    <simpleType name="ectType">
    	<restriction base="decimal">
    		<fractionDigits value="1"></fractionDigits>  
    	</restriction>
    </simpleType>

    <simpleType name="degreeType">
    	<restriction base="string">
    		<enumeration value="Bachelor"></enumeration>
    		<enumeration value="Master"></enumeration>
    		<enumeration value="Doctor"></enumeration>
    	</restriction>
    </simpleType>
</schema>

=== Fercho1992/wangyuhere/trunk/ID2208/XMLProcessing/xml/Transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcript:transcript xmlns:transcript="http://www.example.org/Transcript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Transcript Transcript.xsd ">
  <transcript:name>John</transcript:name>
  <transcript:university>KTH</transcript:university>
  <transcript:degree>Master</transcript:degree>
  <transcript:courses>
  	<transcript:course>
  		<transcript:course_name>Web Service</transcript:course_name>
  		<transcript:grade>A</transcript:grade>
  		<transcript:ect>7.5</transcript:ect>
  	</transcript:course>
  	<transcript:course>
  		<transcript:course_name>Modern Method</transcript:course_name>
  		<transcript:grade>B</transcript:grade>
  		<transcript:ect>7.5</transcript:ect>
  	</transcript:course>
  </transcript:courses>
</transcript:transcript>

=== Fercho1992/wangyuhere/ID2208/XMLProcessing/xml/Transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<transcript:transcript xmlns:transcript="http://www.example.org/Transcript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Transcript Transcript.xsd ">
  <transcript:name>transcript:name</transcript:name>
  <transcript:university>transcript:university</transcript:university>
  <transcript:degree>transcript:degree</transcript:degree>
  <transcript:courses>
  	<transcript:course>
  		<transcript:course_name>transcript:name</transcript:course_name>
  		<transcript:grade>A</transcript:grade>
  		<transcript:ect>7.5</transcript:ect>
  	</transcript:course>
  	<transcript:course>
  		<transcript:course_name>transcript:name</transcript:course_name>
  		<transcript:grade>B</transcript:grade>
  		<transcript:ect>7.5</transcript:ect>
  	</transcript:course>
  </transcript:courses>
</transcript:transcript>
